### ISSUE TITLE
Electron ID requirement not working 100%

### ISSUE THREAD

**Issue by frengelk** [lucaswiens/Susy1LeptonSkimmer#5]
For every good Electron, a lot of the requirements are correct, e.g. PdgId
`ak.sum((abs(electronPdgId[:, 0:1]) == 11))
Out[12]: 10198`

However, ElectronTightId is still of by a small margin
`ak.sum(events.ElectronTightId[:, 0:1])
Out[13]: 9863`

**Comment by lucaswiens** [comment]
This is fixed by redefining the veto leptons in the commit 53eb20d. Now every lepton we consider in this analysis is at least a veto lepton to.
